var annotated_dup =
[
    [ "Architecture", "index.html#autotoc_md1", null ],
    [ "Programming Guide", "index.html#autotoc_md2", [
      [ "oneVPL Session", "index.html#autotoc_md3", [
        [ "Decode Session", "index.html#autotoc_md4", null ],
        [ "Encode Session", "index.html#autotoc_md7", null ],
        [ "Custom Source Readers", "index.html#autotoc_md9", null ]
      ] ],
      [ "Decoding Procedures", "index.html#autotoc_md10", [
        [ "2nd argument to DecodeFrame", "index.html#autotoc_md11", null ]
      ] ],
      [ "Encoding Procedures", "index.html#autotoc_md12", null ]
    ] ],
    [ "FAQ", "index.html#autotoc_md13", [
      [ "What if I will pass encoder's extension buffer to the decoder?", "index.html#autotoc_md14", null ],
      [ "Cool. What if something goes wrong?", "index.html#autotoc_md15", null ]
    ] ],
    [ "oneapi", null, [
      [ "vpl", null, [
        [ "detail", null, [
          [ "_surfCtx__", "structoneapi_1_1vpl_1_1detail_1_1__surfCtx____.html", "structoneapi_1_1vpl_1_1detail_1_1__surfCtx____" ],
          [ "c_api_invoker", "classoneapi_1_1vpl_1_1detail_1_1c__api__invoker.html", "classoneapi_1_1vpl_1_1detail_1_1c__api__invoker" ],
          [ "CAPI", "structoneapi_1_1vpl_1_1detail_1_1CAPI.html", null ],
          [ "sdk_c_api", "structoneapi_1_1vpl_1_1detail_1_1sdk__c__api.html", "structoneapi_1_1vpl_1_1detail_1_1sdk__c__api" ],
          [ "variant", "classoneapi_1_1vpl_1_1detail_1_1variant.html", "classoneapi_1_1vpl_1_1detail_1_1variant" ]
        ] ],
        [ "base_exception", "classoneapi_1_1vpl_1_1base__exception.html", "classoneapi_1_1vpl_1_1base__exception" ],
        [ "base_implementation_capabilities", "classoneapi_1_1vpl_1_1base__implementation__capabilities.html", "classoneapi_1_1vpl_1_1base__implementation__capabilities" ],
        [ "bitstream", "classoneapi_1_1vpl_1_1bitstream.html", "classoneapi_1_1vpl_1_1bitstream" ],
        [ "bitstream_as_dst", "classoneapi_1_1vpl_1_1bitstream__as__dst.html", "classoneapi_1_1vpl_1_1bitstream__as__dst" ],
        [ "bitstream_as_src", "classoneapi_1_1vpl_1_1bitstream__as__src.html", "classoneapi_1_1vpl_1_1bitstream__as__src" ],
        [ "bitstream_file_reader", "classoneapi_1_1vpl_1_1bitstream__file__reader.html", "classoneapi_1_1vpl_1_1bitstream__file__reader" ],
        [ "bitstream_file_reader_name", "classoneapi_1_1vpl_1_1bitstream__file__reader__name.html", "classoneapi_1_1vpl_1_1bitstream__file__reader__name" ],
        [ "bitstream_source_reader", "classoneapi_1_1vpl_1_1bitstream__source__reader.html", "classoneapi_1_1vpl_1_1bitstream__source__reader" ],
        [ "buffer_list", "classoneapi_1_1vpl_1_1buffer__list.html", "classoneapi_1_1vpl_1_1buffer__list" ],
        [ "codec_video_param", "classoneapi_1_1vpl_1_1codec__video__param.html", "classoneapi_1_1vpl_1_1codec__video__param" ],
        [ "cpu_selector", "classoneapi_1_1vpl_1_1cpu__selector.html", "classoneapi_1_1vpl_1_1cpu__selector" ],
        [ "decode_session", "classoneapi_1_1vpl_1_1decode__session.html", "classoneapi_1_1vpl_1_1decode__session" ],
        [ "decode_stat", "classoneapi_1_1vpl_1_1decode__stat.html", "classoneapi_1_1vpl_1_1decode__stat" ],
        [ "decoder_init_header_list", "classoneapi_1_1vpl_1_1decoder__init__header__list.html", "classoneapi_1_1vpl_1_1decoder__init__header__list" ],
        [ "decoder_init_reset_list", "classoneapi_1_1vpl_1_1decoder__init__reset__list.html", "classoneapi_1_1vpl_1_1decoder__init__reset__list" ],
        [ "decoder_process_list", "classoneapi_1_1vpl_1_1decoder__process__list.html", "classoneapi_1_1vpl_1_1decoder__process__list" ],
        [ "decoder_video_param", "classoneapi_1_1vpl_1_1decoder__video__param.html", "classoneapi_1_1vpl_1_1decoder__video__param" ],
        [ "default_selector", "classoneapi_1_1vpl_1_1default__selector.html", "classoneapi_1_1vpl_1_1default__selector" ],
        [ "encode_session", "classoneapi_1_1vpl_1_1encode__session.html", "classoneapi_1_1vpl_1_1encode__session" ],
        [ "encode_stat", "classoneapi_1_1vpl_1_1encode__stat.html", "classoneapi_1_1vpl_1_1encode__stat" ],
        [ "EncodeCtrl", "classoneapi_1_1vpl_1_1EncodeCtrl.html", "classoneapi_1_1vpl_1_1EncodeCtrl" ],
        [ "encoder_init_list", "classoneapi_1_1vpl_1_1encoder__init__list.html", "classoneapi_1_1vpl_1_1encoder__init__list" ],
        [ "encoder_process_list", "classoneapi_1_1vpl_1_1encoder__process__list.html", "classoneapi_1_1vpl_1_1encoder__process__list" ],
        [ "encoder_reset_list", "classoneapi_1_1vpl_1_1encoder__reset__list.html", "classoneapi_1_1vpl_1_1encoder__reset__list" ],
        [ "encoder_video_param", "classoneapi_1_1vpl_1_1encoder__video__param.html", "classoneapi_1_1vpl_1_1encoder__video__param" ],
        [ "ExtAVCEncodedFrameInfo", "classoneapi_1_1vpl_1_1ExtAVCEncodedFrameInfo.html", "classoneapi_1_1vpl_1_1ExtAVCEncodedFrameInfo" ],
        [ "ExtAVCRefListCtrl", "classoneapi_1_1vpl_1_1ExtAVCRefListCtrl.html", "classoneapi_1_1vpl_1_1ExtAVCRefListCtrl" ],
        [ "ExtAVCRefLists", "classoneapi_1_1vpl_1_1ExtAVCRefLists.html", "classoneapi_1_1vpl_1_1ExtAVCRefLists" ],
        [ "ExtAVCRoundingOffset", "classoneapi_1_1vpl_1_1ExtAVCRoundingOffset.html", "classoneapi_1_1vpl_1_1ExtAVCRoundingOffset" ],
        [ "ExtAvcTemporalLayers", "classoneapi_1_1vpl_1_1ExtAvcTemporalLayers.html", "classoneapi_1_1vpl_1_1ExtAvcTemporalLayers" ],
        [ "ExtChromaLocInfo", "classoneapi_1_1vpl_1_1ExtChromaLocInfo.html", "classoneapi_1_1vpl_1_1ExtChromaLocInfo" ],
        [ "ExtCodingOption", "classoneapi_1_1vpl_1_1ExtCodingOption.html", "classoneapi_1_1vpl_1_1ExtCodingOption" ],
        [ "ExtCodingOption2", "classoneapi_1_1vpl_1_1ExtCodingOption2.html", "classoneapi_1_1vpl_1_1ExtCodingOption2" ],
        [ "ExtCodingOption3", "classoneapi_1_1vpl_1_1ExtCodingOption3.html", "classoneapi_1_1vpl_1_1ExtCodingOption3" ],
        [ "ExtCodingOptionSPSPPS", "classoneapi_1_1vpl_1_1ExtCodingOptionSPSPPS.html", "classoneapi_1_1vpl_1_1ExtCodingOptionSPSPPS" ],
        [ "ExtCodingOptionVPS", "classoneapi_1_1vpl_1_1ExtCodingOptionVPS.html", "classoneapi_1_1vpl_1_1ExtCodingOptionVPS" ],
        [ "ExtColorConversion", "classoneapi_1_1vpl_1_1ExtColorConversion.html", "classoneapi_1_1vpl_1_1ExtColorConversion" ],
        [ "ExtContentLightLevelInfo", "classoneapi_1_1vpl_1_1ExtContentLightLevelInfo.html", "classoneapi_1_1vpl_1_1ExtContentLightLevelInfo" ],
        [ "ExtDecodedFrameInfo", "classoneapi_1_1vpl_1_1ExtDecodedFrameInfo.html", "classoneapi_1_1vpl_1_1ExtDecodedFrameInfo" ],
        [ "ExtDecodeErrorReport", "classoneapi_1_1vpl_1_1ExtDecodeErrorReport.html", "classoneapi_1_1vpl_1_1ExtDecodeErrorReport" ],
        [ "ExtDecVideoProcessing", "classoneapi_1_1vpl_1_1ExtDecVideoProcessing.html", "classoneapi_1_1vpl_1_1ExtDecVideoProcessing" ],
        [ "ExtDeviceAffinityMask", "classoneapi_1_1vpl_1_1ExtDeviceAffinityMask.html", "classoneapi_1_1vpl_1_1ExtDeviceAffinityMask" ],
        [ "ExtDirtyRect", "classoneapi_1_1vpl_1_1ExtDirtyRect.html", "classoneapi_1_1vpl_1_1ExtDirtyRect" ],
        [ "ExtEncodedSlicesInfo", "classoneapi_1_1vpl_1_1ExtEncodedSlicesInfo.html", "classoneapi_1_1vpl_1_1ExtEncodedSlicesInfo" ],
        [ "ExtEncodedUnitsInfo", "classoneapi_1_1vpl_1_1ExtEncodedUnitsInfo.html", "classoneapi_1_1vpl_1_1ExtEncodedUnitsInfo" ],
        [ "ExtEncoderCapability", "classoneapi_1_1vpl_1_1ExtEncoderCapability.html", "classoneapi_1_1vpl_1_1ExtEncoderCapability" ],
        [ "ExtEncoderIPCMArea", "classoneapi_1_1vpl_1_1ExtEncoderIPCMArea.html", "classoneapi_1_1vpl_1_1ExtEncoderIPCMArea" ],
        [ "ExtEncoderResetOption", "classoneapi_1_1vpl_1_1ExtEncoderResetOption.html", "classoneapi_1_1vpl_1_1ExtEncoderResetOption" ],
        [ "ExtEncoderROI", "classoneapi_1_1vpl_1_1ExtEncoderROI.html", "classoneapi_1_1vpl_1_1ExtEncoderROI" ],
        [ "extension_buffer", "classoneapi_1_1vpl_1_1extension__buffer.html", "classoneapi_1_1vpl_1_1extension__buffer" ],
        [ "extension_buffer_base", "classoneapi_1_1vpl_1_1extension__buffer__base.html", "classoneapi_1_1vpl_1_1extension__buffer__base" ],
        [ "extension_buffer_trival", "classoneapi_1_1vpl_1_1extension__buffer__trival.html", "classoneapi_1_1vpl_1_1extension__buffer__trival" ],
        [ "extension_buffer_with_ptrs", "classoneapi_1_1vpl_1_1extension__buffer__with__ptrs.html", "classoneapi_1_1vpl_1_1extension__buffer__with__ptrs" ],
        [ "ExtHEVCParam", "classoneapi_1_1vpl_1_1ExtHEVCParam.html", "classoneapi_1_1vpl_1_1ExtHEVCParam" ],
        [ "ExtHEVCRegion", "classoneapi_1_1vpl_1_1ExtHEVCRegion.html", "classoneapi_1_1vpl_1_1ExtHEVCRegion" ],
        [ "ExtHEVCTiles", "classoneapi_1_1vpl_1_1ExtHEVCTiles.html", "classoneapi_1_1vpl_1_1ExtHEVCTiles" ],
        [ "ExtInsertHeaders", "classoneapi_1_1vpl_1_1ExtInsertHeaders.html", "classoneapi_1_1vpl_1_1ExtInsertHeaders" ],
        [ "ExtMasteringDisplayColourVolume", "classoneapi_1_1vpl_1_1ExtMasteringDisplayColourVolume.html", "classoneapi_1_1vpl_1_1ExtMasteringDisplayColourVolume" ],
        [ "ExtMBDisableSkipMap", "classoneapi_1_1vpl_1_1ExtMBDisableSkipMap.html", "classoneapi_1_1vpl_1_1ExtMBDisableSkipMap" ],
        [ "ExtMBForceIntra", "classoneapi_1_1vpl_1_1ExtMBForceIntra.html", "classoneapi_1_1vpl_1_1ExtMBForceIntra" ],
        [ "ExtMBQP", "classoneapi_1_1vpl_1_1ExtMBQP.html", "classoneapi_1_1vpl_1_1ExtMBQP" ],
        [ "ExtMoveRect", "classoneapi_1_1vpl_1_1ExtMoveRect.html", "classoneapi_1_1vpl_1_1ExtMoveRect" ],
        [ "ExtMVOverPicBoundaries", "classoneapi_1_1vpl_1_1ExtMVOverPicBoundaries.html", "classoneapi_1_1vpl_1_1ExtMVOverPicBoundaries" ],
        [ "ExtPartialBitstreamParam", "classoneapi_1_1vpl_1_1ExtPartialBitstreamParam.html", "classoneapi_1_1vpl_1_1ExtPartialBitstreamParam" ],
        [ "ExtPictureTimingSEI", "classoneapi_1_1vpl_1_1ExtPictureTimingSEI.html", "classoneapi_1_1vpl_1_1ExtPictureTimingSEI" ],
        [ "ExtPredWeightTable", "classoneapi_1_1vpl_1_1ExtPredWeightTable.html", "classoneapi_1_1vpl_1_1ExtPredWeightTable" ],
        [ "ExtTimeCode", "classoneapi_1_1vpl_1_1ExtTimeCode.html", "classoneapi_1_1vpl_1_1ExtTimeCode" ],
        [ "ExtVideoSignalInfo", "classoneapi_1_1vpl_1_1ExtVideoSignalInfo.html", "classoneapi_1_1vpl_1_1ExtVideoSignalInfo" ],
        [ "ExtVP9Param", "classoneapi_1_1vpl_1_1ExtVP9Param.html", "classoneapi_1_1vpl_1_1ExtVP9Param" ],
        [ "ExtVP9Segmentation", "classoneapi_1_1vpl_1_1ExtVP9Segmentation.html", "classoneapi_1_1vpl_1_1ExtVP9Segmentation" ],
        [ "ExtVP9TemporalLayers", "classoneapi_1_1vpl_1_1ExtVP9TemporalLayers.html", "classoneapi_1_1vpl_1_1ExtVP9TemporalLayers" ],
        [ "ExtVppAuxData", "classoneapi_1_1vpl_1_1ExtVppAuxData.html", "classoneapi_1_1vpl_1_1ExtVppAuxData" ],
        [ "ExtVPPColorFill", "classoneapi_1_1vpl_1_1ExtVPPColorFill.html", "classoneapi_1_1vpl_1_1ExtVPPColorFill" ],
        [ "ExtVPPComposite", "classoneapi_1_1vpl_1_1ExtVPPComposite.html", "classoneapi_1_1vpl_1_1ExtVPPComposite" ],
        [ "ExtVPPDeinterlacing", "classoneapi_1_1vpl_1_1ExtVPPDeinterlacing.html", "classoneapi_1_1vpl_1_1ExtVPPDeinterlacing" ],
        [ "ExtVPPDenoise", "classoneapi_1_1vpl_1_1ExtVPPDenoise.html", "classoneapi_1_1vpl_1_1ExtVPPDenoise" ],
        [ "ExtVPPDetail", "classoneapi_1_1vpl_1_1ExtVPPDetail.html", "classoneapi_1_1vpl_1_1ExtVPPDetail" ],
        [ "ExtVPPDoNotUse", "classoneapi_1_1vpl_1_1ExtVPPDoNotUse.html", "classoneapi_1_1vpl_1_1ExtVPPDoNotUse" ],
        [ "ExtVPPDoUse", "classoneapi_1_1vpl_1_1ExtVPPDoUse.html", "classoneapi_1_1vpl_1_1ExtVPPDoUse" ],
        [ "ExtVPPFieldProcessing", "classoneapi_1_1vpl_1_1ExtVPPFieldProcessing.html", "classoneapi_1_1vpl_1_1ExtVPPFieldProcessing" ],
        [ "ExtVPPFrameRateConversion", "classoneapi_1_1vpl_1_1ExtVPPFrameRateConversion.html", "classoneapi_1_1vpl_1_1ExtVPPFrameRateConversion" ],
        [ "ExtVPPImageStab", "classoneapi_1_1vpl_1_1ExtVPPImageStab.html", "classoneapi_1_1vpl_1_1ExtVPPImageStab" ],
        [ "ExtVppMctf", "classoneapi_1_1vpl_1_1ExtVppMctf.html", "classoneapi_1_1vpl_1_1ExtVppMctf" ],
        [ "ExtVPPMirroring", "classoneapi_1_1vpl_1_1ExtVPPMirroring.html", "classoneapi_1_1vpl_1_1ExtVPPMirroring" ],
        [ "ExtVPPProcAmp", "classoneapi_1_1vpl_1_1ExtVPPProcAmp.html", "classoneapi_1_1vpl_1_1ExtVPPProcAmp" ],
        [ "ExtVPPRotation", "classoneapi_1_1vpl_1_1ExtVPPRotation.html", "classoneapi_1_1vpl_1_1ExtVPPRotation" ],
        [ "ExtVPPScaling", "classoneapi_1_1vpl_1_1ExtVPPScaling.html", "classoneapi_1_1vpl_1_1ExtVPPScaling" ],
        [ "ExtVPPVideoSignalInfo", "classoneapi_1_1vpl_1_1ExtVPPVideoSignalInfo.html", "classoneapi_1_1vpl_1_1ExtVPPVideoSignalInfo" ],
        [ "file_exception", "classoneapi_1_1vpl_1_1file__exception.html", "classoneapi_1_1vpl_1_1file__exception" ],
        [ "frame_data", "classoneapi_1_1vpl_1_1frame__data.html", "classoneapi_1_1vpl_1_1frame__data" ],
        [ "frame_info", "classoneapi_1_1vpl_1_1frame__info.html", "classoneapi_1_1vpl_1_1frame__info" ],
        [ "frame_source_reader", "classoneapi_1_1vpl_1_1frame__source__reader.html", "classoneapi_1_1vpl_1_1frame__source__reader" ],
        [ "frame_surface", "classoneapi_1_1vpl_1_1frame__surface.html", "classoneapi_1_1vpl_1_1frame__surface" ],
        [ "future", "classoneapi_1_1vpl_1_1future.html", "classoneapi_1_1vpl_1_1future" ],
        [ "gpu_selector", "classoneapi_1_1vpl_1_1gpu__selector.html", "classoneapi_1_1vpl_1_1gpu__selector" ],
        [ "implementation_capabilities", "classoneapi_1_1vpl_1_1implementation__capabilities.html", "classoneapi_1_1vpl_1_1implementation__capabilities" ],
        [ "implementation_capabilities_factory", "classoneapi_1_1vpl_1_1implementation__capabilities__factory.html", "classoneapi_1_1vpl_1_1implementation__capabilities__factory" ],
        [ "implemetation_selector", "classoneapi_1_1vpl_1_1implemetation__selector.html", "classoneapi_1_1vpl_1_1implemetation__selector" ],
        [ "jpeg_decoder_video_param", "classoneapi_1_1vpl_1_1jpeg__decoder__video__param.html", "classoneapi_1_1vpl_1_1jpeg__decoder__video__param" ],
        [ "jpeg_encoder_video_param", "classoneapi_1_1vpl_1_1jpeg__encoder__video__param.html", "classoneapi_1_1vpl_1_1jpeg__encoder__video__param" ],
        [ "layer", "structoneapi_1_1vpl_1_1layer.html", "structoneapi_1_1vpl_1_1layer" ],
        [ "layers", "structoneapi_1_1vpl_1_1layers.html", "structoneapi_1_1vpl_1_1layers" ],
        [ "operation_status", "structoneapi_1_1vpl_1_1operation__status.html", "structoneapi_1_1vpl_1_1operation__status" ],
        [ "payload", "classoneapi_1_1vpl_1_1payload.html", "classoneapi_1_1vpl_1_1payload" ],
        [ "property", "classoneapi_1_1vpl_1_1property.html", "classoneapi_1_1vpl_1_1property" ],
        [ "property_name", "classoneapi_1_1vpl_1_1property__name.html", "classoneapi_1_1vpl_1_1property__name" ],
        [ "raw_frame_file_reader", "classoneapi_1_1vpl_1_1raw__frame__file__reader.html", "classoneapi_1_1vpl_1_1raw__frame__file__reader" ],
        [ "raw_frame_file_reader_by_name", "classoneapi_1_1vpl_1_1raw__frame__file__reader__by__name.html", "classoneapi_1_1vpl_1_1raw__frame__file__reader__by__name" ],
        [ "session", "classoneapi_1_1vpl_1_1session.html", "classoneapi_1_1vpl_1_1session" ],
        [ "source_reader", "classoneapi_1_1vpl_1_1source__reader.html", "classoneapi_1_1vpl_1_1source__reader" ],
        [ "stat", "classoneapi_1_1vpl_1_1stat.html", "classoneapi_1_1vpl_1_1stat" ],
        [ "temporal_frame_allocator", "classoneapi_1_1vpl_1_1temporal__frame__allocator.html", "classoneapi_1_1vpl_1_1temporal__frame__allocator" ],
        [ "video_param", "classoneapi_1_1vpl_1_1video__param.html", "classoneapi_1_1vpl_1_1video__param" ],
        [ "vpp_init_reset_list", "classoneapi_1_1vpl_1_1vpp__init__reset__list.html", "classoneapi_1_1vpl_1_1vpp__init__reset__list" ],
        [ "vpp_process_list", "classoneapi_1_1vpl_1_1vpp__process__list.html", "classoneapi_1_1vpl_1_1vpp__process__list" ],
        [ "vpp_session", "classoneapi_1_1vpl_1_1vpp__session.html", "classoneapi_1_1vpl_1_1vpp__session" ],
        [ "vpp_stat", "classoneapi_1_1vpl_1_1vpp__stat.html", "classoneapi_1_1vpl_1_1vpp__stat" ],
        [ "vpp_video_param", "classoneapi_1_1vpl_1_1vpp__video__param.html", "classoneapi_1_1vpl_1_1vpp__video__param" ]
      ] ]
    ] ],
    [ "Anonymous", "structAnonymous.html", null ],
    [ "mfx3DLutSystemBuffer", "structmfx3DLutSystemBuffer.html", "structmfx3DLutSystemBuffer" ],
    [ "mfx3DLutVideoBuffer", "structmfx3DLutVideoBuffer.html", "structmfx3DLutVideoBuffer" ],
    [ "mfxA2RGB10", "structmfxA2RGB10.html", "structmfxA2RGB10" ],
    [ "mfxAccelerationModeDescription", "structmfxAccelerationModeDescription.html", "structmfxAccelerationModeDescription" ],
    [ "mfxAdapterInfo", "structmfxAdapterInfo.html", "structmfxAdapterInfo" ],
    [ "mfxBitstream", "structmfxBitstream.html", "structmfxBitstream" ],
    [ "mfxBRCFrameParam", "structmfxBRCFrameParam.html", "structmfxBRCFrameParam" ],
    [ "mfxBRCFrameStatus", "structmfxBRCFrameStatus.html", "structmfxBRCFrameStatus" ],
    [ "mfxChannel", "structmfxChannel.html", "structmfxChannel" ],
    [ "mfxComponentInfo", "structmfxComponentInfo.html", "structmfxComponentInfo" ],
    [ "mfxDecoderDescription", "structmfxDecoderDescription.html", "structmfxDecoderDescription" ],
    [ "mfxDecodeStat", "structmfxDecodeStat.html", "structmfxDecodeStat" ],
    [ "mfxEncodedUnitInfo", "structmfxEncodedUnitInfo.html", "structmfxEncodedUnitInfo" ],
    [ "mfxExtAV1FilmGrainParam", "structmfxExtAV1FilmGrainParam.html", "structmfxExtAV1FilmGrainParam" ],
    [ "mfxExtAVCRefListCtrl", "structmfxExtAVCRefListCtrl.html", "structmfxExtAVCRefListCtrl" ],
    [ "mfxExtAVCRefLists", "structmfxExtAVCRefLists.html", "structmfxExtAVCRefLists" ],
    [ "mfxExtAVCRoundingOffset", "structmfxExtAVCRoundingOffset.html", "structmfxExtAVCRoundingOffset" ],
    [ "mfxExtAvcTemporalLayers", "structmfxExtAvcTemporalLayers.html", "structmfxExtAvcTemporalLayers" ],
    [ "mfxExtChromaLocInfo", "structmfxExtChromaLocInfo.html", "structmfxExtChromaLocInfo" ],
    [ "mfxExtCodingOptionSPSPPS", "structmfxExtCodingOptionSPSPPS.html", "structmfxExtCodingOptionSPSPPS" ],
    [ "mfxExtContentLightLevelInfo", "structmfxExtContentLightLevelInfo.html", "structmfxExtContentLightLevelInfo" ],
    [ "mfxExtDecodedFrameInfo", "structmfxExtDecodedFrameInfo.html", "structmfxExtDecodedFrameInfo" ],
    [ "mfxExtDecVideoProcessing", "structmfxExtDecVideoProcessing.html", "structmfxExtDecVideoProcessing" ],
    [ "mfxExtDirtyRect", "structmfxExtDirtyRect.html", "structmfxExtDirtyRect" ],
    [ "mfxExtEncoderCapability", "structmfxExtEncoderCapability.html", "structmfxExtEncoderCapability" ],
    [ "mfxExtEncoderResetOption", "structmfxExtEncoderResetOption.html", "structmfxExtEncoderResetOption" ],
    [ "mfxExtHEVCTiles", "structmfxExtHEVCTiles.html", "structmfxExtHEVCTiles" ],
    [ "mfxExtInCrops", "structmfxExtInCrops.html", "structmfxExtInCrops" ],
    [ "mfxExtInsertHeaders", "structmfxExtInsertHeaders.html", "structmfxExtInsertHeaders" ],
    [ "mfxExtJPEGHuffmanTables", "structmfxExtJPEGHuffmanTables.html", "structmfxExtJPEGHuffmanTables" ],
    [ "mfxExtMoveRect", "structmfxExtMoveRect.html", "structmfxExtMoveRect" ],
    [ "mfxExtMVCTargetViews", "structmfxExtMVCTargetViews.html", "structmfxExtMVCTargetViews" ],
    [ "mfxExtMVOverPicBoundaries", "structmfxExtMVOverPicBoundaries.html", "structmfxExtMVOverPicBoundaries" ],
    [ "mfxExtPictureTimingSEI", "structmfxExtPictureTimingSEI.html", "structmfxExtPictureTimingSEI" ],
    [ "mfxExtPredWeightTable", "structmfxExtPredWeightTable.html", "structmfxExtPredWeightTable" ],
    [ "mfxExtTimeCode", "structmfxExtTimeCode.html", "structmfxExtTimeCode" ],
    [ "mfxExtVideoSignalInfo", "structmfxExtVideoSignalInfo.html", "structmfxExtVideoSignalInfo" ],
    [ "mfxExtVP9Param", "structmfxExtVP9Param.html", "structmfxExtVP9Param" ],
    [ "mfxExtVP9TemporalLayers", "structmfxExtVP9TemporalLayers.html", "structmfxExtVP9TemporalLayers" ],
    [ "mfxExtVPP3DLut", "structmfxExtVPP3DLut.html", "structmfxExtVPP3DLut" ],
    [ "mfxExtVppAuxData", "structmfxExtVppAuxData.html", "structmfxExtVppAuxData" ],
    [ "mfxExtVPPColorFill", "structmfxExtVPPColorFill.html", "structmfxExtVPPColorFill" ],
    [ "mfxExtVPPDenoise", "structmfxExtVPPDenoise.html", "structmfxExtVPPDenoise" ],
    [ "mfxExtVPPDetail", "structmfxExtVPPDetail.html", "structmfxExtVPPDetail" ],
    [ "mfxExtVPPDoNotUse", "structmfxExtVPPDoNotUse.html", "structmfxExtVPPDoNotUse" ],
    [ "mfxExtVppMctf", "structmfxExtVppMctf.html", "structmfxExtVppMctf" ],
    [ "mfxFrameAllocator", "structmfxFrameAllocator.html", "structmfxFrameAllocator" ],
    [ "mfxFrameInfo", "structmfxFrameInfo.html", "structmfxFrameInfo" ],
    [ "mfxFrameSurface1", "structmfxFrameSurface1.html", "structmfxFrameSurface1" ],
    [ "mfxHDLPair", "structmfxHDLPair.html", "structmfxHDLPair" ],
    [ "mfxInfoVPP", "structmfxInfoVPP.html", "structmfxInfoVPP" ],
    [ "mfxInitializationParam", "structmfxInitializationParam.html", "structmfxInitializationParam" ],
    [ "mfxInitParam", "structmfxInitParam.html", "structmfxInitParam" ],
    [ "mfxPayload", "structmfxPayload.html", "structmfxPayload" ],
    [ "mfxRange32U", "structmfxRange32U.html", "structmfxRange32U" ],
    [ "mfxRect", "structmfxRect.html", "structmfxRect" ],
    [ "mfxVariant", "structmfxVariant.html", "structmfxVariant" ],
    [ "MFXVideoDECODE", "classMFXVideoDECODE.html", "classMFXVideoDECODE" ],
    [ "MFXVideoDECODE_VPP", "classMFXVideoDECODE__VPP.html", "classMFXVideoDECODE__VPP" ],
    [ "MFXVideoENCODE", "classMFXVideoENCODE.html", "classMFXVideoENCODE" ],
    [ "MFXVideoSession", "classMFXVideoSession.html", "classMFXVideoSession" ],
    [ "MFXVideoVPP", "classMFXVideoVPP.html", "classMFXVideoVPP" ],
    [ "mfxVP9TemporalLayer", "structmfxVP9TemporalLayer.html", "structmfxVP9TemporalLayer" ],
    [ "mfxVPPCompInputStream", "structmfxVPPCompInputStream.html", "structmfxVPPCompInputStream" ],
    [ "mfxVPPStat", "structmfxVPPStat.html", "structmfxVPPStat" ],
    [ "mfxY416", "structmfxY416.html", "structmfxY416" ]
];