var searchData=
[
  ['encode_5fsession',['encode_session',['../classoneapi_1_1vpl_1_1encode__session.html',1,'oneapi::vpl']]],
  ['encode_5fstat',['encode_stat',['../classoneapi_1_1vpl_1_1encode__stat.html',1,'oneapi::vpl']]],
  ['encodectrl',['EncodeCtrl',['../classoneapi_1_1vpl_1_1EncodeCtrl.html',1,'oneapi::vpl']]],
  ['encoder',['encoder',['../classoneapi_1_1vpl_1_1implementation__capabilities_1_1encoder.html',1,'oneapi::vpl::implementation_capabilities']]],
  ['encoder_5finit_5flist',['encoder_init_list',['../classoneapi_1_1vpl_1_1encoder__init__list.html',1,'oneapi::vpl']]],
  ['encoder_5fprocess_5flist',['encoder_process_list',['../classoneapi_1_1vpl_1_1encoder__process__list.html',1,'oneapi::vpl']]],
  ['encoder_5fprofile',['encoder_profile',['../classoneapi_1_1vpl_1_1implementation__capabilities_1_1encoder__profile.html',1,'oneapi::vpl::implementation_capabilities']]],
  ['encoder_5freset_5flist',['encoder_reset_list',['../classoneapi_1_1vpl_1_1encoder__reset__list.html',1,'oneapi::vpl']]],
  ['encoder_5fvideo_5fparam',['encoder_video_param',['../classoneapi_1_1vpl_1_1encoder__video__param.html',1,'oneapi::vpl']]],
  ['extavcencodedframeinfo',['ExtAVCEncodedFrameInfo',['../classoneapi_1_1vpl_1_1ExtAVCEncodedFrameInfo.html',1,'oneapi::vpl']]],
  ['extavcreflistctrl',['ExtAVCRefListCtrl',['../classoneapi_1_1vpl_1_1ExtAVCRefListCtrl.html',1,'oneapi::vpl']]],
  ['extavcreflists',['ExtAVCRefLists',['../classoneapi_1_1vpl_1_1ExtAVCRefLists.html',1,'oneapi::vpl']]],
  ['extavcroundingoffset',['ExtAVCRoundingOffset',['../classoneapi_1_1vpl_1_1ExtAVCRoundingOffset.html',1,'oneapi::vpl']]],
  ['extavctemporallayers',['ExtAvcTemporalLayers',['../classoneapi_1_1vpl_1_1ExtAvcTemporalLayers.html',1,'oneapi::vpl']]],
  ['extchromalocinfo',['ExtChromaLocInfo',['../classoneapi_1_1vpl_1_1ExtChromaLocInfo.html',1,'oneapi::vpl']]],
  ['extcodingoption',['ExtCodingOption',['../classoneapi_1_1vpl_1_1ExtCodingOption.html',1,'oneapi::vpl']]],
  ['extcodingoption2',['ExtCodingOption2',['../classoneapi_1_1vpl_1_1ExtCodingOption2.html',1,'oneapi::vpl']]],
  ['extcodingoption3',['ExtCodingOption3',['../classoneapi_1_1vpl_1_1ExtCodingOption3.html',1,'oneapi::vpl']]],
  ['extcodingoptionspspps',['ExtCodingOptionSPSPPS',['../classoneapi_1_1vpl_1_1ExtCodingOptionSPSPPS.html',1,'oneapi::vpl']]],
  ['extcodingoptionvps',['ExtCodingOptionVPS',['../classoneapi_1_1vpl_1_1ExtCodingOptionVPS.html',1,'oneapi::vpl']]],
  ['extcolorconversion',['ExtColorConversion',['../classoneapi_1_1vpl_1_1ExtColorConversion.html',1,'oneapi::vpl']]],
  ['extcontentlightlevelinfo',['ExtContentLightLevelInfo',['../classoneapi_1_1vpl_1_1ExtContentLightLevelInfo.html',1,'oneapi::vpl']]],
  ['extdecodedframeinfo',['ExtDecodedFrameInfo',['../classoneapi_1_1vpl_1_1ExtDecodedFrameInfo.html',1,'oneapi::vpl']]],
  ['extdecodeerrorreport',['ExtDecodeErrorReport',['../classoneapi_1_1vpl_1_1ExtDecodeErrorReport.html',1,'oneapi::vpl']]],
  ['extdecvideoprocessing',['ExtDecVideoProcessing',['../classoneapi_1_1vpl_1_1ExtDecVideoProcessing.html',1,'oneapi::vpl']]],
  ['extdeviceaffinitymask',['ExtDeviceAffinityMask',['../classoneapi_1_1vpl_1_1ExtDeviceAffinityMask.html',1,'oneapi::vpl']]],
  ['extdirtyrect',['ExtDirtyRect',['../classoneapi_1_1vpl_1_1ExtDirtyRect.html',1,'oneapi::vpl']]],
  ['extencodedslicesinfo',['ExtEncodedSlicesInfo',['../classoneapi_1_1vpl_1_1ExtEncodedSlicesInfo.html',1,'oneapi::vpl']]],
  ['extencodedunitsinfo',['ExtEncodedUnitsInfo',['../classoneapi_1_1vpl_1_1ExtEncodedUnitsInfo.html',1,'oneapi::vpl']]],
  ['extencodercapability',['ExtEncoderCapability',['../classoneapi_1_1vpl_1_1ExtEncoderCapability.html',1,'oneapi::vpl']]],
  ['extencoderipcmarea',['ExtEncoderIPCMArea',['../classoneapi_1_1vpl_1_1ExtEncoderIPCMArea.html',1,'oneapi::vpl']]],
  ['extencoderresetoption',['ExtEncoderResetOption',['../classoneapi_1_1vpl_1_1ExtEncoderResetOption.html',1,'oneapi::vpl']]],
  ['extencoderroi',['ExtEncoderROI',['../classoneapi_1_1vpl_1_1ExtEncoderROI.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer',['extension_buffer',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxencodectrl_2c_20id_20_3e',['extension_buffer&lt; mfxEncodeCtrl, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextavcencodedframeinfo_2c_20id_20_3e',['extension_buffer&lt; mfxExtAVCEncodedFrameInfo, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextavcreflistctrl_2c_20id_20_3e',['extension_buffer&lt; mfxExtAVCRefListCtrl, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextavcreflists_2c_20id_20_3e',['extension_buffer&lt; mfxExtAVCRefLists, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextavcroundingoffset_2c_20id_20_3e',['extension_buffer&lt; mfxExtAVCRoundingOffset, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextavctemporallayers_2c_20id_20_3e',['extension_buffer&lt; mfxExtAvcTemporalLayers, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextchromalocinfo_2c_20id_20_3e',['extension_buffer&lt; mfxExtChromaLocInfo, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextcodingoption_2c_20id_20_3e',['extension_buffer&lt; mfxExtCodingOption, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextcodingoption2_2c_20id_20_3e',['extension_buffer&lt; mfxExtCodingOption2, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextcodingoption3_2c_20id_20_3e',['extension_buffer&lt; mfxExtCodingOption3, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextcodingoptionspspps_2c_20id_20_3e',['extension_buffer&lt; mfxExtCodingOptionSPSPPS, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextcodingoptionvps_2c_20id_20_3e',['extension_buffer&lt; mfxExtCodingOptionVPS, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextcolorconversion_2c_20id_20_3e',['extension_buffer&lt; mfxExtColorConversion, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextcontentlightlevelinfo_2c_20id_20_3e',['extension_buffer&lt; mfxExtContentLightLevelInfo, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextdecodedframeinfo_2c_20id_20_3e',['extension_buffer&lt; mfxExtDecodedFrameInfo, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextdecodeerrorreport_2c_20id_20_3e',['extension_buffer&lt; mfxExtDecodeErrorReport, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextdecvideoprocessing_2c_20id_20_3e',['extension_buffer&lt; mfxExtDecVideoProcessing, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextdeviceaffinitymask_2c_20id_20_3e',['extension_buffer&lt; mfxExtDeviceAffinityMask, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextdirtyrect_2c_20id_20_3e',['extension_buffer&lt; mfxExtDirtyRect, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextencodedslicesinfo_2c_20id_20_3e',['extension_buffer&lt; mfxExtEncodedSlicesInfo, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextencodedunitsinfo_2c_20id_20_3e',['extension_buffer&lt; mfxExtEncodedUnitsInfo, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextencodercapability_2c_20id_20_3e',['extension_buffer&lt; mfxExtEncoderCapability, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextencoderipcmarea_2c_20id_20_3e',['extension_buffer&lt; mfxExtEncoderIPCMArea, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextencoderresetoption_2c_20id_20_3e',['extension_buffer&lt; mfxExtEncoderResetOption, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextencoderroi_2c_20id_20_3e',['extension_buffer&lt; mfxExtEncoderROI, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxexthevcparam_2c_20id_20_3e',['extension_buffer&lt; mfxExtHEVCParam, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxexthevcregion_2c_20id_20_3e',['extension_buffer&lt; mfxExtHEVCRegion, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxexthevctiles_2c_20id_20_3e',['extension_buffer&lt; mfxExtHEVCTiles, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextinsertheaders_2c_20id_20_3e',['extension_buffer&lt; mfxExtInsertHeaders, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextmasteringdisplaycolourvolume_2c_20id_20_3e',['extension_buffer&lt; mfxExtMasteringDisplayColourVolume, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextmbdisableskipmap_2c_20id_20_3e',['extension_buffer&lt; mfxExtMBDisableSkipMap, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextmbforceintra_2c_20id_20_3e',['extension_buffer&lt; mfxExtMBForceIntra, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextmbqp_2c_20id_20_3e',['extension_buffer&lt; mfxExtMBQP, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextmoverect_2c_20id_20_3e',['extension_buffer&lt; mfxExtMoveRect, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextmvoverpicboundaries_2c_20id_20_3e',['extension_buffer&lt; mfxExtMVOverPicBoundaries, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextpartialbitstreamparam_2c_20id_20_3e',['extension_buffer&lt; mfxExtPartialBitstreamParam, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextpicturetimingsei_2c_20id_20_3e',['extension_buffer&lt; mfxExtPictureTimingSEI, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextpredweighttable_2c_20id_20_3e',['extension_buffer&lt; mfxExtPredWeightTable, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxexttimecode_2c_20id_20_3e',['extension_buffer&lt; mfxExtTimeCode, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvideosignalinfo_2c_20id_20_3e',['extension_buffer&lt; mfxExtVideoSignalInfo, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvp9param_2c_20id_20_3e',['extension_buffer&lt; mfxExtVP9Param, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvp9segmentation_2c_20id_20_3e',['extension_buffer&lt; mfxExtVP9Segmentation, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvp9temporallayers_2c_20id_20_3e',['extension_buffer&lt; mfxExtVP9TemporalLayers, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvppauxdata_2c_20id_20_3e',['extension_buffer&lt; mfxExtVppAuxData, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvppcolorfill_2c_20id_20_3e',['extension_buffer&lt; mfxExtVPPColorFill, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvppcomposite_2c_20id_20_3e',['extension_buffer&lt; mfxExtVPPComposite, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvppdeinterlacing_2c_20id_20_3e',['extension_buffer&lt; mfxExtVPPDeinterlacing, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvppdenoise_2c_20id_20_3e',['extension_buffer&lt; mfxExtVPPDenoise, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvppdetail_2c_20id_20_3e',['extension_buffer&lt; mfxExtVPPDetail, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvppdonotuse_2c_20id_20_3e',['extension_buffer&lt; mfxExtVPPDoNotUse, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvppdouse_2c_20id_20_3e',['extension_buffer&lt; mfxExtVPPDoUse, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvppfieldprocessing_2c_20id_20_3e',['extension_buffer&lt; mfxExtVPPFieldProcessing, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvppframerateconversion_2c_20id_20_3e',['extension_buffer&lt; mfxExtVPPFrameRateConversion, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvppimagestab_2c_20id_20_3e',['extension_buffer&lt; mfxExtVPPImageStab, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvppmctf_2c_20id_20_3e',['extension_buffer&lt; mfxExtVppMctf, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvppmirroring_2c_20id_20_3e',['extension_buffer&lt; mfxExtVPPMirroring, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvppprocamp_2c_20id_20_3e',['extension_buffer&lt; mfxExtVPPProcAmp, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvpprotation_2c_20id_20_3e',['extension_buffer&lt; mfxExtVPPRotation, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvppscaling_2c_20id_20_3e',['extension_buffer&lt; mfxExtVPPScaling, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_3c_20mfxextvppvideosignalinfo_2c_20id_20_3e',['extension_buffer&lt; mfxExtVPPVideoSignalInfo, ID &gt;',['../classoneapi_1_1vpl_1_1extension__buffer.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5fbase',['extension_buffer_base',['../classoneapi_1_1vpl_1_1extension__buffer__base.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival',['extension_buffer_trival',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextavcencodedframeinfo_2c_20mfx_5fextbuff_5fencoded_5fframe_5finfo_20_3e',['extension_buffer_trival&lt; mfxExtAVCEncodedFrameInfo, MFX_EXTBUFF_ENCODED_FRAME_INFO &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextavcreflistctrl_2c_20mfx_5fextbuff_5favc_5freflist_5fctrl_20_3e',['extension_buffer_trival&lt; mfxExtAVCRefListCtrl, MFX_EXTBUFF_AVC_REFLIST_CTRL &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextavcreflists_2c_20mfx_5fextbuff_5favc_5freflists_20_3e',['extension_buffer_trival&lt; mfxExtAVCRefLists, MFX_EXTBUFF_AVC_REFLISTS &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextavcroundingoffset_2c_20mfx_5fextbuff_5favc_5frounding_5foffset_20_3e',['extension_buffer_trival&lt; mfxExtAVCRoundingOffset, MFX_EXTBUFF_AVC_ROUNDING_OFFSET &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextavctemporallayers_2c_20mfx_5fextbuff_5favc_5ftemporal_5flayers_20_3e',['extension_buffer_trival&lt; mfxExtAvcTemporalLayers, MFX_EXTBUFF_AVC_TEMPORAL_LAYERS &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextchromalocinfo_2c_20mfx_5fextbuff_5fchroma_5floc_5finfo_20_3e',['extension_buffer_trival&lt; mfxExtChromaLocInfo, MFX_EXTBUFF_CHROMA_LOC_INFO &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextcodingoption_2c_20mfx_5fextbuff_5fcoding_5foption_20_3e',['extension_buffer_trival&lt; mfxExtCodingOption, MFX_EXTBUFF_CODING_OPTION &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextcodingoption2_2c_20mfx_5fextbuff_5fcoding_5foption2_20_3e',['extension_buffer_trival&lt; mfxExtCodingOption2, MFX_EXTBUFF_CODING_OPTION2 &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextcodingoption3_2c_20mfx_5fextbuff_5fcoding_5foption3_20_3e',['extension_buffer_trival&lt; mfxExtCodingOption3, MFX_EXTBUFF_CODING_OPTION3 &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextcolorconversion_2c_20mfx_5fextbuff_5fvpp_5fcolor_5fconversion_20_3e',['extension_buffer_trival&lt; mfxExtColorConversion, MFX_EXTBUFF_VPP_COLOR_CONVERSION &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextcontentlightlevelinfo_2c_20mfx_5fextbuff_5fcontent_5flight_5flevel_5finfo_20_3e',['extension_buffer_trival&lt; mfxExtContentLightLevelInfo, MFX_EXTBUFF_CONTENT_LIGHT_LEVEL_INFO &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextdecodedframeinfo_2c_20mfx_5fextbuff_5fdecoded_5fframe_5finfo_20_3e',['extension_buffer_trival&lt; mfxExtDecodedFrameInfo, MFX_EXTBUFF_DECODED_FRAME_INFO &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextdecodeerrorreport_2c_20mfx_5fextbuff_5fdecode_5ferror_5freport_20_3e',['extension_buffer_trival&lt; mfxExtDecodeErrorReport, MFX_EXTBUFF_DECODE_ERROR_REPORT &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextdecvideoprocessing_2c_20mfx_5fextbuff_5fdec_5fvideo_5fprocessing_20_3e',['extension_buffer_trival&lt; mfxExtDecVideoProcessing, MFX_EXTBUFF_DEC_VIDEO_PROCESSING &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextdirtyrect_2c_20mfx_5fextbuff_5fdirty_5frectangles_20_3e',['extension_buffer_trival&lt; mfxExtDirtyRect, MFX_EXTBUFF_DIRTY_RECTANGLES &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextencodercapability_2c_20mfx_5fextbuff_5fencoder_5fcapability_20_3e',['extension_buffer_trival&lt; mfxExtEncoderCapability, MFX_EXTBUFF_ENCODER_CAPABILITY &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextencoderresetoption_2c_20mfx_5fextbuff_5fencoder_5freset_5foption_20_3e',['extension_buffer_trival&lt; mfxExtEncoderResetOption, MFX_EXTBUFF_ENCODER_RESET_OPTION &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextencoderroi_2c_20mfx_5fextbuff_5fencoder_5froi_20_3e',['extension_buffer_trival&lt; mfxExtEncoderROI, MFX_EXTBUFF_ENCODER_ROI &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxexthevcparam_2c_20mfx_5fextbuff_5fhevc_5fparam_20_3e',['extension_buffer_trival&lt; mfxExtHEVCParam, MFX_EXTBUFF_HEVC_PARAM &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxexthevcregion_2c_20mfx_5fextbuff_5fhevc_5fregion_20_3e',['extension_buffer_trival&lt; mfxExtHEVCRegion, MFX_EXTBUFF_HEVC_REGION &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxexthevctiles_2c_20mfx_5fextbuff_5fhevc_5ftiles_20_3e',['extension_buffer_trival&lt; mfxExtHEVCTiles, MFX_EXTBUFF_HEVC_TILES &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextinsertheaders_2c_20mfx_5fextbuff_5finsert_5fheaders_20_3e',['extension_buffer_trival&lt; mfxExtInsertHeaders, MFX_EXTBUFF_INSERT_HEADERS &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextmasteringdisplaycolourvolume_2c_20mfx_5fextbuff_5fmastering_5fdisplay_5fcolour_5fvolume_20_3e',['extension_buffer_trival&lt; mfxExtMasteringDisplayColourVolume, MFX_EXTBUFF_MASTERING_DISPLAY_COLOUR_VOLUME &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextmoverect_2c_20mfx_5fextbuff_5fmoving_5frectangles_20_3e',['extension_buffer_trival&lt; mfxExtMoveRect, MFX_EXTBUFF_MOVING_RECTANGLES &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextmvoverpicboundaries_2c_20mfx_5fextbuff_5fmv_5fover_5fpic_5fboundaries_20_3e',['extension_buffer_trival&lt; mfxExtMVOverPicBoundaries, MFX_EXTBUFF_MV_OVER_PIC_BOUNDARIES &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextpartialbitstreamparam_2c_20mfx_5fextbuff_5fpartial_5fbitstream_5fparam_20_3e',['extension_buffer_trival&lt; mfxExtPartialBitstreamParam, MFX_EXTBUFF_PARTIAL_BITSTREAM_PARAM &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextpicturetimingsei_2c_20mfx_5fextbuff_5fpicture_5ftiming_5fsei_20_3e',['extension_buffer_trival&lt; mfxExtPictureTimingSEI, MFX_EXTBUFF_PICTURE_TIMING_SEI &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextpredweighttable_2c_20mfx_5fextbuff_5fpred_5fweight_5ftable_20_3e',['extension_buffer_trival&lt; mfxExtPredWeightTable, MFX_EXTBUFF_PRED_WEIGHT_TABLE &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxexttimecode_2c_20mfx_5fextbuff_5ftime_5fcode_20_3e',['extension_buffer_trival&lt; mfxExtTimeCode, MFX_EXTBUFF_TIME_CODE &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextvideosignalinfo_2c_20mfx_5fextbuff_5fvideo_5fsignal_5finfo_20_3e',['extension_buffer_trival&lt; mfxExtVideoSignalInfo, MFX_EXTBUFF_VIDEO_SIGNAL_INFO &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextvp9param_2c_20mfx_5fextbuff_5fvp9_5fparam_20_3e',['extension_buffer_trival&lt; mfxExtVP9Param, MFX_EXTBUFF_VP9_PARAM &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextvp9temporallayers_2c_20mfx_5fextbuff_5fvp9_5ftemporal_5flayers_20_3e',['extension_buffer_trival&lt; mfxExtVP9TemporalLayers, MFX_EXTBUFF_VP9_TEMPORAL_LAYERS &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextvppauxdata_2c_20mfx_5fextbuff_5fvpp_5fauxdata_20_3e',['extension_buffer_trival&lt; mfxExtVppAuxData, MFX_EXTBUFF_VPP_AUXDATA &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextvppcolorfill_2c_20mfx_5fextbuff_5fvpp_5fcolorfill_20_3e',['extension_buffer_trival&lt; mfxExtVPPColorFill, MFX_EXTBUFF_VPP_COLORFILL &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextvppdeinterlacing_2c_20mfx_5fextbuff_5fvpp_5fdeinterlacing_20_3e',['extension_buffer_trival&lt; mfxExtVPPDeinterlacing, MFX_EXTBUFF_VPP_DEINTERLACING &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextvppdenoise_2c_20mfx_5fextbuff_5fvpp_5fdenoise_20_3e',['extension_buffer_trival&lt; mfxExtVPPDenoise, MFX_EXTBUFF_VPP_DENOISE &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextvppdetail_2c_20mfx_5fextbuff_5fvpp_5fdetail_20_3e',['extension_buffer_trival&lt; mfxExtVPPDetail, MFX_EXTBUFF_VPP_DETAIL &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextvppfieldprocessing_2c_20mfx_5fextbuff_5fvpp_5ffield_5fprocessing_20_3e',['extension_buffer_trival&lt; mfxExtVPPFieldProcessing, MFX_EXTBUFF_VPP_FIELD_PROCESSING &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextvppframerateconversion_2c_20mfx_5fextbuff_5fvpp_5fframe_5frate_5fconversion_20_3e',['extension_buffer_trival&lt; mfxExtVPPFrameRateConversion, MFX_EXTBUFF_VPP_FRAME_RATE_CONVERSION &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextvppimagestab_2c_20mfx_5fextbuff_5fvpp_5fimage_5fstabilization_20_3e',['extension_buffer_trival&lt; mfxExtVPPImageStab, MFX_EXTBUFF_VPP_IMAGE_STABILIZATION &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextvppmctf_2c_20mfx_5fextbuff_5fvpp_5fmctf_20_3e',['extension_buffer_trival&lt; mfxExtVppMctf, MFX_EXTBUFF_VPP_MCTF &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextvppmirroring_2c_20mfx_5fextbuff_5fvpp_5fmirroring_20_3e',['extension_buffer_trival&lt; mfxExtVPPMirroring, MFX_EXTBUFF_VPP_MIRRORING &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextvppprocamp_2c_20mfx_5fextbuff_5fvpp_5fprocamp_20_3e',['extension_buffer_trival&lt; mfxExtVPPProcAmp, MFX_EXTBUFF_VPP_PROCAMP &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextvpprotation_2c_20mfx_5fextbuff_5fvpp_5frotation_20_3e',['extension_buffer_trival&lt; mfxExtVPPRotation, MFX_EXTBUFF_VPP_ROTATION &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextvppscaling_2c_20mfx_5fextbuff_5fvpp_5fscaling_20_3e',['extension_buffer_trival&lt; mfxExtVPPScaling, MFX_EXTBUFF_VPP_SCALING &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5ftrival_3c_20mfxextvppvideosignalinfo_2c_20mfx_5fextbuff_5fvpp_5fvideo_5fsignal_5finfo_20_3e',['extension_buffer_trival&lt; mfxExtVPPVideoSignalInfo, MFX_EXTBUFF_VPP_VIDEO_SIGNAL_INFO &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__trival.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5fwith_5fptrs',['extension_buffer_with_ptrs',['../classoneapi_1_1vpl_1_1extension__buffer__with__ptrs.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5fwith_5fptrs_3c_20mfxencodectrl_2c_200_20_3e',['extension_buffer_with_ptrs&lt; mfxEncodeCtrl, 0 &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__with__ptrs.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5fwith_5fptrs_3c_20mfxextcodingoptionspspps_2c_20mfx_5fextbuff_5fcoding_5foption_5fspspps_20_3e',['extension_buffer_with_ptrs&lt; mfxExtCodingOptionSPSPPS, MFX_EXTBUFF_CODING_OPTION_SPSPPS &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__with__ptrs.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5fwith_5fptrs_3c_20mfxextcodingoptionvps_2c_20mfx_5fextbuff_5fcoding_5foption_5fvps_20_3e',['extension_buffer_with_ptrs&lt; mfxExtCodingOptionVPS, MFX_EXTBUFF_CODING_OPTION_VPS &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__with__ptrs.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5fwith_5fptrs_3c_20mfxextdeviceaffinitymask_2c_20mfx_5fextbuff_5fdevice_5faffinity_5fmask_20_3e',['extension_buffer_with_ptrs&lt; mfxExtDeviceAffinityMask, MFX_EXTBUFF_DEVICE_AFFINITY_MASK &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__with__ptrs.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5fwith_5fptrs_3c_20mfxextencodedslicesinfo_2c_20mfx_5fextbuff_5fencoded_5fslices_5finfo_20_3e',['extension_buffer_with_ptrs&lt; mfxExtEncodedSlicesInfo, MFX_EXTBUFF_ENCODED_SLICES_INFO &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__with__ptrs.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5fwith_5fptrs_3c_20mfxextencodedunitsinfo_2c_20mfx_5fextbuff_5fencoded_5funits_5finfo_20_3e',['extension_buffer_with_ptrs&lt; mfxExtEncodedUnitsInfo, MFX_EXTBUFF_ENCODED_UNITS_INFO &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__with__ptrs.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5fwith_5fptrs_3c_20mfxextencoderipcmarea_2c_20mfx_5fextbuff_5fencoder_5fipcm_5farea_20_3e',['extension_buffer_with_ptrs&lt; mfxExtEncoderIPCMArea, MFX_EXTBUFF_ENCODER_IPCM_AREA &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__with__ptrs.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5fwith_5fptrs_3c_20mfxextmbdisableskipmap_2c_20mfx_5fextbuff_5fmb_5fdisable_5fskip_5fmap_20_3e',['extension_buffer_with_ptrs&lt; mfxExtMBDisableSkipMap, MFX_EXTBUFF_MB_DISABLE_SKIP_MAP &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__with__ptrs.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5fwith_5fptrs_3c_20mfxextmbforceintra_2c_20mfx_5fextbuff_5fmb_5fforce_5fintra_20_3e',['extension_buffer_with_ptrs&lt; mfxExtMBForceIntra, MFX_EXTBUFF_MB_FORCE_INTRA &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__with__ptrs.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5fwith_5fptrs_3c_20mfxextmbqp_2c_20mfx_5fextbuff_5fmbqp_20_3e',['extension_buffer_with_ptrs&lt; mfxExtMBQP, MFX_EXTBUFF_MBQP &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__with__ptrs.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5fwith_5fptrs_3c_20mfxextvp9segmentation_2c_20mfx_5fextbuff_5fvp9_5fsegmentation_20_3e',['extension_buffer_with_ptrs&lt; mfxExtVP9Segmentation, MFX_EXTBUFF_VP9_SEGMENTATION &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__with__ptrs.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5fwith_5fptrs_3c_20mfxextvppcomposite_2c_20mfx_5fextbuff_5fcoding_5foption_5fvps_20_3e',['extension_buffer_with_ptrs&lt; mfxExtVPPComposite, MFX_EXTBUFF_CODING_OPTION_VPS &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__with__ptrs.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5fwith_5fptrs_3c_20mfxextvppdonotuse_2c_20mfx_5fextbuff_5fvpp_5fdonotuse_20_3e',['extension_buffer_with_ptrs&lt; mfxExtVPPDoNotUse, MFX_EXTBUFF_VPP_DONOTUSE &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__with__ptrs.html',1,'oneapi::vpl']]],
  ['extension_5fbuffer_5fwith_5fptrs_3c_20mfxextvppdouse_2c_20mfx_5fextbuff_5fvpp_5fdouse_20_3e',['extension_buffer_with_ptrs&lt; mfxExtVPPDoUse, MFX_EXTBUFF_VPP_DOUSE &gt;',['../classoneapi_1_1vpl_1_1extension__buffer__with__ptrs.html',1,'oneapi::vpl']]],
  ['exthevcparam',['ExtHEVCParam',['../classoneapi_1_1vpl_1_1ExtHEVCParam.html',1,'oneapi::vpl']]],
  ['exthevcregion',['ExtHEVCRegion',['../classoneapi_1_1vpl_1_1ExtHEVCRegion.html',1,'oneapi::vpl']]],
  ['exthevctiles',['ExtHEVCTiles',['../classoneapi_1_1vpl_1_1ExtHEVCTiles.html',1,'oneapi::vpl']]],
  ['extinsertheaders',['ExtInsertHeaders',['../classoneapi_1_1vpl_1_1ExtInsertHeaders.html',1,'oneapi::vpl']]],
  ['extmasteringdisplaycolourvolume',['ExtMasteringDisplayColourVolume',['../classoneapi_1_1vpl_1_1ExtMasteringDisplayColourVolume.html',1,'oneapi::vpl']]],
  ['extmbdisableskipmap',['ExtMBDisableSkipMap',['../classoneapi_1_1vpl_1_1ExtMBDisableSkipMap.html',1,'oneapi::vpl']]],
  ['extmbforceintra',['ExtMBForceIntra',['../classoneapi_1_1vpl_1_1ExtMBForceIntra.html',1,'oneapi::vpl']]],
  ['extmbqp',['ExtMBQP',['../classoneapi_1_1vpl_1_1ExtMBQP.html',1,'oneapi::vpl']]],
  ['extmoverect',['ExtMoveRect',['../classoneapi_1_1vpl_1_1ExtMoveRect.html',1,'oneapi::vpl']]],
  ['extmvoverpicboundaries',['ExtMVOverPicBoundaries',['../classoneapi_1_1vpl_1_1ExtMVOverPicBoundaries.html',1,'oneapi::vpl']]],
  ['extpartialbitstreamparam',['ExtPartialBitstreamParam',['../classoneapi_1_1vpl_1_1ExtPartialBitstreamParam.html',1,'oneapi::vpl']]],
  ['extpicturetimingsei',['ExtPictureTimingSEI',['../classoneapi_1_1vpl_1_1ExtPictureTimingSEI.html',1,'oneapi::vpl']]],
  ['extpredweighttable',['ExtPredWeightTable',['../classoneapi_1_1vpl_1_1ExtPredWeightTable.html',1,'oneapi::vpl']]],
  ['exttimecode',['ExtTimeCode',['../classoneapi_1_1vpl_1_1ExtTimeCode.html',1,'oneapi::vpl']]],
  ['extvideosignalinfo',['ExtVideoSignalInfo',['../classoneapi_1_1vpl_1_1ExtVideoSignalInfo.html',1,'oneapi::vpl']]],
  ['extvp9param',['ExtVP9Param',['../classoneapi_1_1vpl_1_1ExtVP9Param.html',1,'oneapi::vpl']]],
  ['extvp9segmentation',['ExtVP9Segmentation',['../classoneapi_1_1vpl_1_1ExtVP9Segmentation.html',1,'oneapi::vpl']]],
  ['extvp9temporallayers',['ExtVP9TemporalLayers',['../classoneapi_1_1vpl_1_1ExtVP9TemporalLayers.html',1,'oneapi::vpl']]],
  ['extvppauxdata',['ExtVppAuxData',['../classoneapi_1_1vpl_1_1ExtVppAuxData.html',1,'oneapi::vpl']]],
  ['extvppcolorfill',['ExtVPPColorFill',['../classoneapi_1_1vpl_1_1ExtVPPColorFill.html',1,'oneapi::vpl']]],
  ['extvppcomposite',['ExtVPPComposite',['../classoneapi_1_1vpl_1_1ExtVPPComposite.html',1,'oneapi::vpl']]],
  ['extvppdeinterlacing',['ExtVPPDeinterlacing',['../classoneapi_1_1vpl_1_1ExtVPPDeinterlacing.html',1,'oneapi::vpl']]],
  ['extvppdenoise',['ExtVPPDenoise',['../classoneapi_1_1vpl_1_1ExtVPPDenoise.html',1,'oneapi::vpl']]],
  ['extvppdetail',['ExtVPPDetail',['../classoneapi_1_1vpl_1_1ExtVPPDetail.html',1,'oneapi::vpl']]],
  ['extvppdonotuse',['ExtVPPDoNotUse',['../classoneapi_1_1vpl_1_1ExtVPPDoNotUse.html',1,'oneapi::vpl']]],
  ['extvppdouse',['ExtVPPDoUse',['../classoneapi_1_1vpl_1_1ExtVPPDoUse.html',1,'oneapi::vpl']]],
  ['extvppfieldprocessing',['ExtVPPFieldProcessing',['../classoneapi_1_1vpl_1_1ExtVPPFieldProcessing.html',1,'oneapi::vpl']]],
  ['extvppframerateconversion',['ExtVPPFrameRateConversion',['../classoneapi_1_1vpl_1_1ExtVPPFrameRateConversion.html',1,'oneapi::vpl']]],
  ['extvppimagestab',['ExtVPPImageStab',['../classoneapi_1_1vpl_1_1ExtVPPImageStab.html',1,'oneapi::vpl']]],
  ['extvppmctf',['ExtVppMctf',['../classoneapi_1_1vpl_1_1ExtVppMctf.html',1,'oneapi::vpl']]],
  ['extvppmirroring',['ExtVPPMirroring',['../classoneapi_1_1vpl_1_1ExtVPPMirroring.html',1,'oneapi::vpl']]],
  ['extvppprocamp',['ExtVPPProcAmp',['../classoneapi_1_1vpl_1_1ExtVPPProcAmp.html',1,'oneapi::vpl']]],
  ['extvpprotation',['ExtVPPRotation',['../classoneapi_1_1vpl_1_1ExtVPPRotation.html',1,'oneapi::vpl']]],
  ['extvppscaling',['ExtVPPScaling',['../classoneapi_1_1vpl_1_1ExtVPPScaling.html',1,'oneapi::vpl']]],
  ['extvppvideosignalinfo',['ExtVPPVideoSignalInfo',['../classoneapi_1_1vpl_1_1ExtVPPVideoSignalInfo.html',1,'oneapi::vpl']]]
];
